### ISSUE TITLE
Clicking on empty config field logs error

### ISSUE THREAD

**Issue by enbyd** [lntricate1/EntityVisualizer#1]
## Description

(see title)

## Reproduce

1. Go to entity visualizer config screen
2. Click on editable config field
3. Erase contents of field
4. Click newly empty field
(optional step between 3 and 4: Click outside of config field)

What I expect to happen:
No error is logged, since nothing about the text field has changed (cursor is still there)
(including optional step: I expect the text field to revert to the previously saved state when clicking away without a new valid value. This already happens when closing the menu or toggling the renderer.)
 
What actually happens:
Nothing visually changes in game, but I get a long error trace in my log.
(including optional step: text field stays empty with no error when clicking away, then gives error if I click back into the field)

## Environment

- Minecraft version: 1.17.1 fabric
- EntityVisualizer version: 1.0.2
- malilib version: 1.17.1-0.10.0-dev.26

## Log

[Render thread/WARN]: Failed to set config value for duration from the string ''
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:678) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
	at fi.dy.masa.malilib.config.options.ConfigInteger.setValueFromString(ConfigInteger.java:135) ~[malilib-fabric-1.17.1-0.10.0-dev.26.jar:?]
	at me.lntricate.entityvisualizer.malilib.widgets.EWidgetConfigOption.applyNewValueToConfig(EWidgetConfigOption.java:168) ~[entityvisualizer-mc1.17.1-v1.0.2.jar:?]
	at me.lntricate.entityvisualizer.malilib.widgets.EWidgetConfigOption.onMouseClickedImpl(EWidgetConfigOption.java:126) ~[entityvisualizer-mc1.17.1-v1.0.2.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetContainer.onMouseClicked(WidgetContainer.java:74) ~[malilib-fabric-1.17.1-0.10.0-dev.26.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetListBase.onMouseClicked(WidgetListBase.java:109) ~[malilib-fabric-1.17.1-0.10.0-dev.26.jar:?]
	at fi.dy.masa.malilib.gui.widgets.WidgetListConfigOptionsBase.onMouseClicked(WidgetListConfigOptionsBase.java:47) ~[malilib-fabric-1.17.1-0.10.0-dev.26.jar:?]
	at me.lntricate.entityvisualizer.malilib.gui.EGuiListBase.onMouseClicked(EGuiListBase.java:94) ~[entityvisualizer-mc1.17.1-v1.0.2.jar:?]
	at me.lntricate.entityvisualizer.malilib.gui.EGuiConfigsBase.onMouseClicked(EGuiConfigsBase.java:186) ~[entityvisualizer-mc1.17.1-v1.0.2.jar:?]
	at fi.dy.masa.malilib.gui.GuiBase.method_25402(GuiBase.java:210) ~[malilib-fabric-1.17.1-0.10.0-dev.26.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:490) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) [lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1137) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.13.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]

**Comment by enbyd** [comment]
It turns out this logger spam exists in tweakeroo, so maybe this goes higher up the chain into malilib. Post edited to include malilib version (most up-to-date version for 1.17.1).
##
Expected behavior in the (optional) reproduction steps related to https://github.com/lntricate1/EntityVisualizer/issues/2
